default_platform(:ios)

platform :ios do
	desc "Push a new dev build to AppCenter"
	lane :dev do
		increment_build_number_in_plist(
			scheme: "Spring Dev")

		update_info_plist(
			plist_path: "./Spring/Dev-Info.plist",
			block: proc do |plist|
				appCredential = plist["AppCredentials"]
				appCredential["API_FBM_SERVER_URL"] = ENV["TEST_SERVER_URL"]
			end
			)

		cert
		sigh(force: true)

		build_app(
			scheme: "Spring Dev",
			export_method: "ad-hoc",
			workspace: "Spring.xcworkspace",
			include_bitcode: false,
			clean: true,
			output_directory: "./ipas")

		sentry_upload_dsym(
			auth_token: ENV['SENTRY_AUTH_TOKEN'],
			org_slug: 'bitmark-inc',
			project_slug: 'fbm-spring',
			dsym_path: './ipas/Spring.app.dSYM.zip')

		appcenter_upload(
			api_token: ENV["APPCENTER_API_TOKEN"],
			owner_name: "support-zzd0-28",
			owner_type: "organization",
			app_name: "Spring-Internal",
			notify_testers: true)
	end

	desc "Push a new enterprise build to AppCenter"
	lane :enterprise do
		increment_build_number_in_plist(
			scheme: "Spring Inhouse")

		update_info_plist(
			plist_path: "./Spring/Inhouse-Info.plist",
			block: proc do |plist|
				appCredential = plist["AppCredentials"]
				appCredential["API_FBM_SERVER_URL"] = ENV["SERVER_URL"]
			end
			)

		cert
		sigh(force: true)

		build_app(
			scheme: "Spring Inhouse",
			export_method: "enterprise",
			workspace: "Spring.xcworkspace",
			include_bitcode: false,
			clean: false,
			output_directory: "./ipas")

		sentry_upload_dsym(
			auth_token: ENV['SENTRY_AUTH_TOKEN'],
			org_slug: 'bitmark-inc',
			project_slug: 'fbm-spring',
			dsym_path: './ipas/Spring.app.dSYM.zip'
		)

		appcenter_upload(
			api_token: ENV["APPCENTER_API_TOKEN"],
			owner_name: "support-zzd0-28",
			owner_type: "organization",
			app_name: "Spring-Inhouse",
			notify_testers: true
		)
  end
end
